name: phosphoricons_generator
maintainer: Rurick Maqueo Poisot @rurickdev
version: 2.0.0
homepage: https://phosphoricons.com/
repository: https://github.com/phosphor-icons/phosphor-flutter
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  archive: ^3.3.6
  code_builder: ^4.4.0
  dart_style: ^2.3.0
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.1
